apiVersion: apps/v1
kind: Deployment
metadata:
  name: "nginx-deployment"
  namespace: "nginx"
spec:
  selector:
    matchLabels:
      app: "nginx-label"
  replicas: 3
  template:
    metadata:
      labels:
        app: "nginx-label"
    spec:
      containers:
      - image: nginx:1.24.0
        imagePullPolicy: Always
        name: "nginx-container"
        ports:
        - containerPort: 80

