apiVersion: v1
kind: Service
metadata:
  name: "nginx-service"
  namespace: "nginx"
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: "nginx-label"

